export default {
  LOAD: "LOAD",
  ADD_TODO: "ADD_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  DELETE_TODO: "DELETE_TODO",
  TOGGLE_ARCHIVE_TODO: "TOGGLE_ARCHIVE_TODO",
  TOGGLE_COMPLETE_TODO: "TOGGLE_COMPLETE_TODO",
  CHANGE_GROUPING: "CHANGE_GROUPING",
  CHANGE_SHOW: "CHANGE_SHOW",
  NONE: "NONE",
  BY_CONTEXT: "CONTEXT",
  BY_PROJECT: "PROJECT",
  SHOW_UNARCHIVED: "SHOW_UNARCHIVED",
  SHOW_ARCHIVED: "SHOW_ARCHIVED",

  TODAY: "today",
  TOMORROW: "tomorrow",
  THIS_WEEK: "this_week",
  ALL: "all",

  SEARCH: "SEARCH",

  NOTIFICATION: "NOTIFICATION",
  ADD_EDIT_NOTIFICATION: "ADD_EDIT_NOTIFICATION",

  LOAD_SUCCESS: "LOAD_SUCCESS",
  SAVE_SUCCESS: "SAVE_SUCCESS",
  BACKEND_FAILURE: "BACKEND_FAILURE",
}
