export default {
  ADD_TODO: "ADD_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  DELETE_TODO: "DELETE_TODO",
  TOGGLE_ARCHIVE_TODO: "TOGGLE_ARCHIVE_TODO",
  TOGGLE_COMPLETE_TODO: "TOGGLE_COMPLETE_TODO",
  CHANGE_GROUPING: "CHANGE_GROUPING",
  CHANGE_SHOW: "CHANGE_SHOW",
  NONE: "NONE",
  BY_CONTEXT: "CONTEXT",
  BY_PROJECT: "PROJECT",
  SHOW_UNARCHIVED: "SHOW_UNARCHIVED",
  SHOW_ARCHIVED: "SHOW_ARCHIVED"
}

